config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  mount Sidekiq::Web => "/sidekiq" # monitoring console
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :admins, path: "admins", controllers: { sessions: "admins/sessions" }, skip: %i[registrations password]
  authenticated :admin do
    root "admins/games#index", as: :authenticated_admin_root
    namespace :admins do
      resources :games do
        member do
          patch "toggle_fetching", to: "games#toggle_fetching"
        end
      end
    end
  end
  resources :games, only: %i[show]
  root "home#index"
end

app/models/game.rb
# == Schema Information
#
# Table name: games
#
#  access_token :string           not null
#  created_at   :datetime         not null
#  id           :integer          not null, primary key
#  question     :string           not null
#  title        :string           not null
#  updated_at   :datetime         not null
#  video_id     :integer          not null
#

# Model for video live games
class Game < ApplicationRecord
  has_many :answers, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :correct_answers, dependent: :destroy
  accepts_nested_attributes_for :answers, allow_destroy: true
  validates :video_id, :access_token, presence: true

  def self.search(search)
    where("title iLIKE :search", search: "%#{search}%").order(title: :asc)
  end
end

app/controllers/admins/games_controller.rb
# Controller for Admin Game CMS
class Admins::GamesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_game, only: %i[show edit update destroy]

  def index
    @games = Game.search(params[:search]).page(params[:page]).per(10).decorate
  end

  def new
    @game = Game.new(answers: [Answer.new])
  end

  def create
    @game = Game.create(game_params)
  end

  def show
  end

  def edit
  end

  def update
    @game.update(game_params)
  end

  def destroy
    @game.destroy
  end

  private

  def set_game
    @game = Game.find(params[:id]).decorate
  end

  def game_params
    params.require(:game).permit(
      :title, :question, :video_id, :access_token,
      answers_attributes: %i[id words points _destroy]
    )
  end
end

app/controllers/games_controller.rb
# Controller for Admin Game CMS
class GamesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_game, only: %i[show]

  def show
    @answers = @game.answers.decorate
  end

  private

  def set_game
    @game = Game.find(params[:id]).decorate
  end
end

app/helpers/games_helper.rb
module GamesHelper
  def generate_answer_list(game)
    game.answers.decorate.each do |answer|
      concat content_tag(:li, answer.words_and_points, class: "answer_list")
    end
  end

  def generate_fetch_toggle(game)
    game.is_fetching?
  end

  def generate_answer_input(game)
    game.answers.each do |answer|
      inner_span = content_tag(
        :span, "",
        class: "ion-ios-close-empty answer-remove"
      )
      inner_tag = tag(
        "input", name: "answer[]", type: "text",
        value: answer, class: "answer", placeholder: "scope"
      )
      concat content_tag(:div, inner_span + inner_tag, class: "answer-container")
    end
  end
end

app/views/admins/games/_answer_fields.html.erb
<div class='nested-fields admin-input'>
   <div class="field">
     <%= f.text_field :words %>
   </div>
   <div class="field">
     <%= f.number_field :points %>
   </div>
   <%= link_to_remove_association f do %>
      <span class="remove_object">&times;</span>
   <% end %>
 </div>

app/views/admins/games/_game_instance.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <h5><%= game.new_record? ? "ADD GAME" : "EDIT GAME"%></h5>
          </div>
        </div>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-xs-1 col-sm-1 col-md-3 col-lg-3"></div>
          <div class="col-xs-10 col-sm-10 col-md-6 col-lg-6">
            <% method = game.new_record? ? :post : :put %>
            <% url_action = game.new_record? ? "create" : "update" %>
            <%= form_for game, url: { action: url_action, controller: "admins/games" }, multipart: true, method: method, remote: true do |f| %>
              <div class="admin-input-container">
                <div class="admin-label">
                    <%= label_tag(:title, "Title") %> <%=content_tag('span', "", id: "error_title", class: "admin-input-error")%>
                </div>
                <div class="admin-input">
                  <%= f.text_field :title, placeholder: "Title", tabindex: 0  %>
                </div>
              </div>

              <div class="admin-input-container">
                <div class="admin-label">
                    <%= label_tag(:question, "Question") %> <%=content_tag('span', "", id: "error_question", class: "admin-input-error")%>
                </div>
                <div class="admin-input">
                  <%= f.text_field :question, placeholder: "Question"  %>
                </div>
              </div>

              <div class="admin-input-container">
                <div class="admin-label">
                    <%= label_tag(:answers, "Answers and Points") %>
                </div>
                <div id='answers'>
                  <%= f.fields_for :answers do |answer| %>
                    <%= render 'admins/games/answer_fields', :f => answer %>
                  <% end %>
                  <div class='links'>
                    <%= link_to_add_association f, :answers do %>
                       <span class="ion-android-add-circle"></span>
                    <% end %>
                  </div>
                </div>
              </div>

              <div class="admin-input-container">
                <div class="admin-label">
                    <%= label_tag(:video_id, "VIDEO ID") %> <%=content_tag('span', "", id: "error_video_id", class: "admin-input-error")%>
                </div>
                <div class="admin-input">
                  <%= f.text_field :video_id, placeholder: "VIDEO ID"  %>
                </div>
              </div>

              <div class="admin-input-container">
                <div class="admin-label">
                    <%= label_tag(:access_token, "Access Token") %> <%=content_tag('span', "", id: "error_access_token", class: "admin-input-error")%>
                </div>
                <div class="admin-input">
                  <%= f.text_field :access_token, placeholder: "Access Token"  %>
                </div>
              </div>

              <div class="admin-input-container">
                  <div class="admin-form-action-container">
                    <%= f.submit "SAVE", class: "normal btn" %>
                  </div>
              </div>
            <% end %>
          </div>
          <div class="col-xs-1 col-sm-1 col-md-3 col-lg-3"></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admins/games/_game_resources.html.erb
<% games.each do |game|%>
  <div class="row single-object game-object" id="gameID<%=game.id%>">
    <%= render partial: 'admins/games/game_row', locals: { game: game } %>
  </div>
<% end %>

<% if games.next_page || games.prev_page %>
  <div class="row resource-paginate">
    <%= paginate games, remote: true  %>
  </div>
<% end %>

app/views/admins/games/_game_row.html.erb
<div class="col-md-3  text-wrap"><span class="orange-titles"><%=game.title%></span></div>
<div class="col-md-3  text-wrap"><span class="orange-titles"><%=game.question%></span></div>
<div class="col-md-2  text-wrap"><%generate_answer_list(game)%></div>
<div class="col-md-1  text-wrap"><%=game.video_id%></div>
<div class="col-md-1  text-wrap"><%= game.access_token %></div>
<div class="col-md-2 actions">
  <%=link_to edit_admins_game_path(game), remote: true, class: "success" do %>
    <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>EDIT
  <% end %>
  <%=link_to admins_game_path(game), remote: true, method: :delete, data: { confirm: "Are you sure?" }, class: "warning" do %>
    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>DELETE
  <% end %>
</div>

app/views/admins/games/create.js.erb
<% if @game.errors.blank? %>
  var modal = document.getElementById('allModal');
  modal.style.display = "none";

  var html = "<div class='row single-object game-object' id='gameID<%=@game.id%>'>" +
              "<%= escape_javascript( render partial: 'admins/games/game_row', locals: { game: @game.decorate } ) %>" +
              "</div>";
  if ($(".game-object:first").length > 0) {
    $(".game-object:first").before(html);
  }
  else {
    $("#gameResources").prepend(html);
  }
<% else %>
  <% @game.errors.messages.each do |k,v| %>
    var errorID = "<%=k.to_s%>";
    var errorMsg = "<%=v.first%>";
    $("#error_"+errorID).show().html(errorMsg).delay(5000).fadeOut(400);
  <% end %>
<% end %>

app/views/admins/games/destroy.js.erb
var game_id = "<%=@game.id%>";
$("#gameID"+game_id).fadeOut().remove();
$("#modalLoading").css('display','none');

app/views/admins/games/edit.js.erb
html = "<%= escape_javascript( render partial: 'admins/games/game_instance', locals: { game: @game.decorate }) %>";
modalShow(html);

app/views/admins/games/index.html.erb
<% provide(:title, "Admin Games Types") %>
<div class="row single-page-resources">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-12 col-sm-7 col-md-7 col-lg-8"><h5>GAMES</h5></div>
          <div class="col-xs-7 col-sm-3 col-md-3 col-lg-3 flex-end">
            <%=form_tag(admins_games_path, method: :get, remote: true) do %>
              <i class="fa fa-search"></i>
              <%=text_field_tag 'search', nil, placeholder: "Search", id: "searchResources" %>
            <% end %>
          </div>
          <div class="col-xs-5 col-sm-2 col-md-2 col-lg-1 flex-end">
            <%=link_to new_admins_game_path, remote: true, class: "add-object" do %>
              CREATE <i class="fa fa-plus"></i>
            <% end %>
          </div>
        </div>
      </div>
      <div class="panel-body single-page-resources">
        <div class="row resource-headers">
          <div class="col-md-3"><h5>Title</h5></div>
          <div class="col-md-3"><h5>Question</h5></div>
          <div class="col-md-2"><h5>Answers</h5></div>
          <div class="col-md-1"><h5>FB Video ID</h5></div>
          <div class="col-md-1"><h5>Access Token</h5></div>
          <div class="col-md-2"><h5>Action</h5></div>
        </div>
        <div id="gameResources">
          <%= render partial: 'admins/games/game_resources', locals: { games: @games } %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admins/games/index.js.erb
$("#gameResources").html("<%= escape_javascript( render partial: 'admins/games/game_resources', locals: { games: @games } ) %>");

app/views/admins/games/new.js.erb
html = "<%= escape_javascript( render partial: 'admins/games/game_instance', locals: { game: @game.decorate }) %>";
modalShow(html);

app/views/admins/games/update.js.erb
<% if @game.errors.blank? %>
  var modal = document.getElementById('allModal');
  modal.style.display = "none";
  var game_id = "<%=@game.id%>";
  $("#gameID"+game_id).html("<%= escape_javascript( render partial: 'admins/games/game_row', locals: { game: @game } ) %>");
<% else %>
  <% @game.errors.messages.each do |k,v| %>
    var errorID = "<%=k.to_s%>";
    var errorMsg = "<%=v.first%>";
    $("#error_"+errorID).show().html(errorMsg).delay(5000).fadeOut(400);
  <% end %>
<% end %>