config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  mount Sidekiq::Web => "/sidekiq" # monitoring console
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :admins, path: "admins", controllers: { sessions: "admins/sessions" }, skip: %i[registrations password]
  authenticated :admin do
    root "admins/games#index", as: :authenticated_admin_root
    namespace :admins do
      resources :games do
        member do
          patch "toggle_fetching", to: "games#toggle_fetching"
        end
      end
    end
  end
  resources :games, only: %i[show]
  root "home#index"
end

app/views/shared/admin/_footer.html.erb
<footer>
  <a href="#">About Us</a>
  <a href="#">Contact Us</a>
  <span>&#9400; 2018 Gorated Innovation lab Inc.</span>
</footer>

app/views/shared/admin/_nav.html.erb
<nav class="admin-nav">
  <div class="nav-container">
      <div class="logo">
        <%= link_to authenticated_admin_root_path do %>
          <%=image_tag("defensil.png", alt: '')%>
        <% end %>
      </div>

      <div class="resources">
        <ul>
          <li><%= link_to "GAMES", admins_games_path %></li>
        </ul>
      </div>

      <div class="admin-settings">
        <div class="dropdown">
          <a href="#" class="dropdown-toggle" id="dropdownAdminSettings" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            Welcome, Admin! <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" aria-labelledby="dropdownAdminSettings">
            <li><%=link_to 'Sign Out', destroy_admin_session_path, method: :delete %></li>
          </ul>
        </div>
      </div>
  </div>
</nav>

<!-- The Modal -->
<div id="allModal" class="modal">
  <span class="close">&times;</span>
  <!-- Modal content -->
  <div class="modal-content">
    <div id="objectHtml">Object html here</div>
  </div>
</div>